import { ERROR_MESSAGES } from '../messages/messages';

export enum ErrorCode {
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
  MISSING_INFORMATION = 'MISSING_INFORMATION',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  DATABASE_ERROR = 'DATABASE_ERROR',
  SESSION_CREATION_ERROR = 'SESSION_CREATION_ERROR',
  SESSION_INVALID = 'SESSION_INVALID',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
}

export interface ErrorResponse {
  code: ErrorCode;
  message: string;
  timestamp: Date;
}

export const ERROR_CODE_MESSAGES: Record<ErrorCode, string> = {
  [ErrorCode.EMAIL_NOT_FOUND]: ERROR_MESSAGES.EMAIL_NOT_FOUND,
  [ErrorCode.MISSING_INFORMATION]: ERROR_MESSAGES.MISSING_INFORMATION,
  [ErrorCode.INCORRECT_PASSWORD]: ERROR_MESSAGES.INCORRECT_PASSWORD,
  [ErrorCode.INVALID_CREDENTIALS]: ERROR_MESSAGES.INVALID_CREDENTIALS,
  [ErrorCode.USER_NOT_FOUND]: ERROR_MESSAGES.USER_NOT_FOUND,
  [ErrorCode.DATABASE_ERROR]: ERROR_MESSAGES.DATABASE_ERROR,
  [ErrorCode.SESSION_CREATION_ERROR]: ERROR_MESSAGES.SESSION_CREATION_ERROR,
  [ErrorCode.SESSION_INVALID]: ERROR_MESSAGES.SESSION_INVALID,
  [ErrorCode.SESSION_EXPIRED]: ERROR_MESSAGES.SESSION_EXPIRED,
};
